# ---------
# Packaging
# ---------

# Simple build backend which looks for packages in the `src` directory.
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# -------
# Project
# -------

[project]
name = "f1_data_visualisation"
requires-python = ">=3.13"
version = "0.1.0"

dependencies = [
    "alembic>=1.17.2",
    "attrs>=25.4.0",
    "environs>=14.5.0",
    "factory-boy>=3.3.3",
    "fastapi>=0.128.0",
    "fastf1>=3.7.0",
    "import-linter>=2.9",
    "invoke>=2.2.1",
    "psycopg2>=2.9.11",
    "sqlalchemy>=2.0.45",
    "structlog>=25.5.0",
    "uvicorn>=0.40.0",
]

[dependency-groups]
dev = [
    # Testing
    "pytest",

    # Localdev
    "pre-commit",

    # Linting
    # We pin the version so that we don't update ruff and cause a lot of linting errors. Upgrades should be done
    # deliberately.
    "ruff<0.14.10",
    # Type checking
    "ty",
]

# ---------
# Hatchling
# ---------

[tool.hatch.build.targets.wheel]
packages = ["src/f1_data_visualisation"]


# ----
# Ruff
# ----

[tool.ruff]
line-length = 99

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN002", # Missing type annotation for *{name}
    "ANN003", # Missing type annotation for **{name}
    "ANN204", # Missing type annotation for dunder method
    "ANN401", # Dynamically typed expressions (typing.Any) are disallowed in {name}
    "ARG", # flake8-unused-arguments
    "COM812", # Trailing comma missing
    "D1", # Missing docstring in {}
    "D200", # One-line docstring should fit on one line
    "D203", # 1 blank line required before class docstring
    "D212", # Multi-line docstring summary should start at the first line
    "D301", # Use r""" if any backslashes in a docstring
    "D406", # Section name should end with a newline ("{name}")
    "D407", # Missing dashed underline after section ("{name}")
    "D408", # Section underline should be in the line following the section's name ("{name}")
    "D413", # Missing blank line after last section ("{name}")
    "E501", # Line too long
    "EM", # flake8-errmsg
    "ERA001", # Found commented-out code
    "FIX", # flake8-fixme
    "PLC0414", # Import alias does not rename original package
    "PLR0904", # Too many public methods (x > 20)
    "PLR0911", # Too many return statements (x > 6)
    "PLR0912", # Too many branches (x > 12)
    "PLR0913", # Too many arguments to function call (x > 5)
    "PLR2004", # Magic value used in comparison, consider replacing 4 with a constant variable
    "PLR5501", # Use `elif` instead of `else` then `if`, to reduce indentation
    "PLR6301", # Method `foo` could be a function or static method
    "PT003",  # {} is implied in {}
    "PYI041", # Use `float` instead of `int | float`
    "RUF001", # String contains ambiguous `'` (RIGHT SINGLE QUOTATION MARK). Did you mean ``` (GRAVE ACCENT)?
    "S101",  # Use of `assert` detected
    "S311",  # Standard pseudo-random generators are not suitable for cryptographic purposes
    "SIM102",  # Use a single `if` statement instead of nested `if` statements
    "SIM108",  # Use ternary operator ... instead of `if`-`else`-block
    "SIM910",  # Use `{"foo": "bar"}.get(value)` instead of `{"foo": "bar"}.get(value, None)`
    "TC001", # https://docs.astral.sh/ruff/rules/typing-only-first-party-import/
    "TC002", # https://docs.astral.sh/ruff/rules/typing-only-third-party-import/
    "TC003", # https://docs.astral.sh/ruff/rules/typing-only-standard-library-import/
    "TD002", # Missing author in TODO
    "TD003", # Missing issue link on the line following this TODO
    "TRY003", # Avoid specifying long messages outside the exception class
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
    "F401", # Allow unused imports in __init__ files as these are convenience imports
]
"tests/**" = [
    "ANN",  # Allow missing type annotations in tests
    "SLF001",  # Private member accessed: {}
]
"src/f1_data_visualisation/data/migrations/versions/**" = [
    "D400",  # First line should end with a period
    "D415",  # First line should end with a period, question mark, or exclamation point
    "N999",  # Invalid module name: {}
]


[tool.ruff.lint.isort]
lines-after-imports = 2
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "project",
    "local-folder",
]

[tool.ruff.lint.isort.sections]
"project" = [
    "f1_data_visualisation",
    "tests",
]

[tool.ruff.lint.flake8-builtins]
strict-checking = true


# --
# Ty
# --

[tool.ty.src]
include = ["src"]
exclude = ["build", "tests"]


# ------
# Pytest
# ------

[tool.pytest.ini_options]
python_files = "test_*.py"
testpaths = "tests"
pythonpath = ["."]


# -------------
# Import linter
# -------------

[tool.importlinter]
root_package = "f1_data_visualisation"
include_external_packages = true

[[tool.importlinter.contracts]]
name = "Top level layers"
type = "layers"
exhaustive = true
containers = ["f1_data_visualisation"]
layers = [
    # Entrypoint
    "main",
    # Application layer
    "application",
    # Domain layer
    "domain",
    # Data layer
    "data",
    # Anywhere can import config
    "config",

]

[[tool.importlinter.contracts]]
name = "Domain: queries cannot import from operations"
type = "forbidden"
source_modules = ["f1_data_visualisation.domain.*.queries"]
forbidden_modules = ["f1_data_visualisation.domain.*.operations"]

[[tool.importlinter.contracts]]
name = "Domain modules hierarchy"
type = "layers"
containers = ["f1_data_visualisation.domain"]
layers = [
    "driver_stats",
    "vendor_adapters",
    "drivers",
    "sessions",
    "rounds",
    "seasons",
]
