"""
Add initial base model

Revision ID: cd8f79d99e52
Revises:
Create Date: 2025-12-31 11:34:13.712845

"""

from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "cd8f79d99e52"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
