"""
Add unique constraint to round model

Revision ID: 1a7ef7c98865
Revises: 9f919330b6d9
Create Date: 2026-01-11 19:50:30.286982

"""

from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "1a7ef7c98865"
down_revision: str | Sequence[str] | None = "9f919330b6d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_number_season", "rounds", ["number", "season_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_number_season", "rounds", type_="unique")
    # ### end Alembic commands ###
