"""
Fix type of time columns

Revision ID: 9f919330b6d9
Revises: 0c4e4e096fd8
Create Date: 2026-01-09 23:00:43.249571

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9f919330b6d9"
down_revision: str | Sequence[str] | None = "0c4e4e096fd8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "driver_session_results",
        "time",
        existing_type=sa.VARCHAR(),
        type_=sa.Float(),
        existing_nullable=True,
        postgresql_using="time::double precision",
    )
    op.alter_column(
        "driver_session_results",
        "q1_time",
        existing_type=sa.VARCHAR(),
        type_=sa.Float(),
        existing_nullable=True,
        postgresql_using="time::double precision",
    )
    op.alter_column(
        "driver_session_results",
        "q2_time",
        existing_type=sa.VARCHAR(),
        type_=sa.Float(),
        existing_nullable=True,
        postgresql_using="time::double precision",
    )
    op.alter_column(
        "driver_session_results",
        "q3_time",
        existing_type=sa.VARCHAR(),
        type_=sa.Float(),
        existing_nullable=True,
        postgresql_using="time::double precision",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "driver_session_results",
        "q3_time",
        existing_type=sa.Float(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "driver_session_results",
        "q2_time",
        existing_type=sa.Float(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "driver_session_results",
        "q1_time",
        existing_type=sa.Float(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "driver_session_results",
        "time",
        existing_type=sa.Float(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
