"""
Add points and position to season data

Revision ID: 5f91fb7206ab
Revises: 1a7ef7c98865
Create Date: 2026-01-18 20:35:40.323735

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "5f91fb7206ab"
down_revision: str | Sequence[str] | None = "1a7ef7c98865"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("driver_seasons", sa.Column("position", sa.Integer(), nullable=True))
    op.add_column(
        "driver_seasons", sa.Column("points", sa.Float(), server_default="0.0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("driver_seasons", "points")
    op.drop_column("driver_seasons", "position")
    # ### end Alembic commands ###
