DOWNLOAD_RESULTS_FOR_SEASON_STARTED = "download.results-for-season.started"
DOWNLOAD_RESULTS_FOR_SEASON_COMPLETED = "download.results-for-season.completed"
DOWNLOAD_ROUND_SKIPPED = "download.round.skipped"
DOWNLOAD_ROUND_COMPLETED = "download.round.completed"

STORE_DRIVER_SEASON_RESULTS_STARTED = "store.driver-season-results.started"
STORE_DRIVER_SEASON_RESULTS_DRIVER_SAVED = "store.driver-season-results.driver-saved"
STORE_DRIVER_SEASON_RESULTS_ERRORED = "store.driver-season-results.errored"
STORE_DRIVER_SEASON_RESULTS_DRIVER_ERRORED = "store.driver-season-results.driver-errored"
STORE_DRIVER_SEASON_RESULTS_COMPLETED = "store.driver-season-results.completed"
